config/routes.rb
Etymology::Application.routes.draw do
  devise_for :admins

  root :to => "home#index"

  get '/admin' => 'admin#index'

  get '/landing_page' => 'home#landing_page'

  post 'interested_user' => 'home#interested_user', as: 'interested_user'

  get '/users' => 'admin#users'

  resources :rootwords
  resources :non_rootwords

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/non_rootword.rb
class NonRootword < ActiveRecord::Base
    belongs_to :rootword

    serialize :meaning
    serialize :usages

    validates :word, presence: true
    validates :word, uniqueness: true
end

app/models/rootword.rb
class Rootword < ActiveRecord::Base
  serialize :usages
end

app/models/users.rb
class Users < ActiveRecord::Base
    validates_uniqueness_of :email
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @rootwords = Rootword.all
    @non_rootwords = NonRootword.all
  end

  def users
      @interested_user_emails = Users.all
      render json: @interested_user_emails
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :store_location
  after_filter :set_cache_buster


  private
  def store_location
    return if devise_controller?
    session[:user_return_to] = request.url if request.get?
  end

  def set_cache_buster
    response.headers['Cache-Control'] = 'no-cache, no-store, max-age=0, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @non_rootwords = NonRootword.all
        render 'index' and return if ['development', 'test'].include?(Rails.env)
        render 'landing_page'
    end

    def landing_page
    end

    def interested_user
        filtered_params = filter_email_param(params)
        Users.create(filtered_params)
        render 'thank_you'
    end

    private

    def filter_email_param(params)
        params.require('user').permit(:email)
    end

end

app/controllers/non_rootwords_controller.rb
class NonRootwordsController < ApplicationController
    before_filter :authenticate_admin!, only: :create

    def create
        filtered_params = filter_non_root_word_params(params)
        NonRootword.create(filtered_params)
        redirect_to(admin_path)
    end

    def index
        render json: NonRootword.all
    end

    private
    def filter_non_root_word_params params
        filtered_params = params.require('non_root_word').permit(:word, :meaning, :id, :usages)
        filtered_params[:usages] = filtered_params[:usages].split(',')
        filtered_params[:meaning] = filtered_params[:meaning].split(',')
        filtered_params[:rootword] = Rootword.where(id: filtered_params.delete(:id)).first
        filtered_params
    end
end

app/controllers/rootwords_controller.rb
class RootwordsController < ApplicationController
  def create
    filtered_params = filter_root_word_params(params)
    Rootword.create(filtered_params)
    redirect_to(admin_path)
  end

  def index
      render json: Rootword.all
  end

  private
  def filter_root_word_params params
    params.require('root_word').permit(:word, :meaning, :usages)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_new_non_root_word_form.html.erb
<div class="text-center">
  <%= form_tag non_rootwords_path, role: 'form', class: 'form-horizontal', id: 'root_word' do %>

      <div class="form-group col-sm-6">
        <label class="col-sm-3 text-right">Word</label>

        <div class="col-sm-9">
          <%= text_field :non_root_word, :word, placeholder: 'word', title: 'root word', required: true, class: "form-control" %>
        </div>
      </div>

      <div class="form-group col-sm-6">
        <label class="col-sm-3 text-right">Root word</label>

        <div class="col-sm-9">
          <%= select('non_root_word', 'id', @rootwords.map { |rw| [rw.word, rw.id] }, {include_blank: 'Select Root Word'}, {required: true, class: 'form-control', title: 'rootword'}) %>
        </div>
      </div>

      <div class="form-group col-sm-6">
        <label class="col-sm-3 text-right">Meaning</label>

        <div class="col-sm-9">
          <%= text_area :non_root_word, :meaning, placeholder: 'meaning (comma separated)', title: 'meaning', required: true, class: "form-control", rows: 3 %>
        </div>
      </div>

      <div class="form-group col-sm-6">
        <label class="col-sm-3 text-right">Usage</label>

        <div class="col-sm-9">
          <%= text_area :non_root_word, :usages, placeholder: 'usages (comma separated)', title: 'usages', required: true, class: "form-control", rows: 3 %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-3 col-sm-offset-5">
          <div class="space-bar"></div>
          <button type="submit" class="btn btn-primary btn-block">Add</button>
        </div>
      </div>
  <% end %>
</div>

<div class="space-bar"></div>

app/views/admin/_new_root_word_form.html.erb
<div class="text-center row">
  <div class="space-bar"></div>
  <%= form_tag rootwords_path, role: 'form', class: 'form-inline', id: 'root_word' do %>

      <div class="form-group col-sm-3">
        <label class="text-right col-sm-3 visible-lg visible-md">Word</label>

        <div class="col-sm-9">
          <%= text_field :root_word, :word, placeholder: 'root word', title: 'root word', required: true, class: "form-control" %>
        </div>
      </div>

      <div class="form-group col-sm-3">
        <label class="pull-left text-right col-sm-4 visible-lg visible-md">Meaning</label>

        <div class="col-sm-8">
          <%= text_field :root_word, :meaning, placeholder: 'meaning', title: 'meaning', required: true, class: "form-control" %>
        </div>
      </div>

      <div class="form-group col-sm-4">
        <label class="pull-left text-right col-sm-3 visible-lg visible-md">Usage</label>

        <div class="col-sm-9">
          <%= text_field :root_word, :usages, placeholder: 'usages', title: 'usages', required: true, class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-sm-2">
        <div class="col-sm-12">
          <button type="submit" class="btn btn-block btn-primary">Add</button>
        </div>
      </div>
  <% end %>
</div>
<div class="space-bar"></div>
<div class="space-bar"></div>

app/views/admin/_non_root_words_table.html.erb
<div class="col-sm-12 medium-table-container">
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Word</th>
      <th class="hidden-xs">Meaning</th>
      <th>Root word</th>
      <th class="hidden-xs">Usages</th>
    </tr>
    </thead>

    <tbody>
    <% @non_rootwords.each do |non_rootword| %>
        <tr>
          <td><%= non_rootword.word %></td>
          <td class="hidden-xs">
            <% meanings = '' %>
            <%- non_rootword.meaning.each do |meaning| %>
                <% meanings = meanings + ', ' + meaning %>
            <% end %>
            <%= meanings.from(1) %>
          </td>
          <td><%= non_rootword.rootword.word %></td>
          <td class="hidden-xs">
            <ul>
              <%- non_rootword.usages.each do |usage| %>
                  <li><%= usage %></li>
              <% end %>
            </ul>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/_root_words_table.html.erb
<div class="col-sm-12 medium-table-container">
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Root Word</th>
      <th>Meaning</th>
      <th>Usages</th>
    </tr>
    </thead>

    <tbody>
    <% @rootwords.each do |rootword| %>
        <tr>
          <td><%= rootword.word %></td>
          <td><%= rootword.meaning %></td>
          <td><%= rootword.usages %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/index.html.erb
<div class="container">
  <div class="space-bar"></div>
  <div class="page-header">
    <h1>Admin dashboard
      <small>Add root and other words</small>
    </h1>
  </div>


  <ul class="nav nav-tabs">
    <li class="active"><a href="#root_words" data-toggle="tab">Root Words</a></li>
    <li><a href="#non_root_words" data-toggle="tab">Non Root Words</a></li>
  </ul>


  <div class="tab-content">
    <div class="tab-pane active" id="root_words">
      <div class="space-bar"></div>

      <div class="row">
        <div class="col-sm-12">
          <%= render partial: 'new_root_word_form' %>
        </div>
      </div>

      <div class="row">
        <%= render partial: 'root_words_table' %>
      </div>

    </div>

    <div class="tab-pane" id="non_root_words">
      <div class="space-bar"></div>
      <div class="row">
        <div class="col-sm-12">
          <%= render partial: 'new_non_root_word_form' %>
        </div>
      </div>

      <div class="row">
        <%= render partial: 'non_root_words_table' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.erb
<div class="container">
  <div class="space-bar"></div>
  <div class="page-header">
    <h1>Welcome to Etymology-Lab
      <small>an Effort to help you improve your vocabulary</small>
    </h1>
  </div>


  <div class="row">
    <div class="col-sm-12 medium-table-container">
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>Word</th>
          <th class="hidden-xs">Meaning</th>
          <th>Root word</th>
          <th class="hidden-xs">Usages</th>
        </tr>
        </thead>

        <tbody>
        <% @non_rootwords.each do |non_rootword| %>
            <tr id="<%= non_rootword.word %>">
              <td>
                <button class="btn btn-link btn-block btn-unstyled" data-target-modal="non-rootword-modal" data-target='#non-rootword-modal' data-toggle="modal">
                  <div class="hidden non-rootword-data" data-non-rootword="<%= non_rootword.to_json %>"></div>
                  <%= non_rootword.word %>
                </button>
              </td>
              <td class="hidden-xs">
                <% meanings = '' %>
                <%- non_rootword.meaning.each do |meaning| %>
                    <% meanings = meanings + ', ' + meaning %>
                <% end %>
                <%= meanings.from(1) %>
              </td>
              <td>
                <button class="btn btn-link btn-block btn-unstyled" data-target-modal="rootword-modal" data-target='#rootword-modal' data-toggle="modal">
                  <div class="hidden rootword-data" data-rootword="<%= non_rootword.rootword.to_json %>"></div>
                  <%= non_rootword.rootword.word %>
                </button>
              </td>
              <td class="hidden-xs">
                <ul>
                <%- non_rootword.usages.each do |usage| %>
                    <li><%= usage %></li>
                <% end %>
                </ul>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render partial: 'shared/non_rootword_modal' %>
<%= render partial: 'shared/rootword_modal' %>

app/views/home/landing_page.html.erb
<div class="container text-center">
  <div class="space-bar"></div>
  <div class="page-header">
    <h1>Welcome to Etymology-Lab
      <small>An effort to help you improve your vocabulary</small>
    </h1>
  </div>
  <div class="well">

    <div class="row">
      <div class="col-sm-12">
        <h2>Hello my friend</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <h4 class="alert alert-info">My site isn't quite ready. I'm trying to get the basic version out live
          soon.</h4>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <p class="lead" >This site shall enable you to improve your vocabulary using the classic etymology way.
          <br/>Getting the root words and moving up the ladder. <br/>
          I myself am a learner and want to help others like
          me who are desperately trying to improve their vocabulary.
        <ul class="text-left col-sm-offset-3">
          <li>You can also do well in your Competitive Exams.</li>
          <li>You can now be impressive at your office.</li>
          <li>You can travel the world without the language being a barrier to effective communication.</li>
        </ul>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 text-center">
        <h4>Would you like to receive a one time Email when the basic version of the site goes live?</h4>
        <%= form_tag interested_user_path, role: 'form', class: 'form-horizontal', id: 'interested-users' do %>

          <div class="form-group">
            <label class="col-sm-1 col-sm-offset-3" for="exampleInputEmail2">Email:</label>
            <div class="col-sm-3">
              <%= text_field :user, :email, placeholder: 'email', title: 'email', required: true, class: "form-control" %>
            </div>
            <div class="col-sm-1">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/thank_you.html.erb
<div class="container">
  <div class="space-bar"></div>
  <div class="page-header">
    <h1>Thank you</h1>
  </div>
  <div class="well">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h4>Thank you for your interest. This motivates me to work harder for going live.</h4>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etymology</title>
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

  <%= render partial: 'shared/stylesheets' %>
  <%= render partial: 'shared/header_scripts' %>
</head>
<body class="etymology">
    <div class="app-container">
      <%= render partial: 'shared/header' %>
      <%= yield %>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render partial: 'shared/footer_scripts' %>

</body>
</html>

app/views/shared/_footer_scripts.html.erb
<%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' %>
<%= javascript_include_tag '//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js' %>

<!--[if lt IE 9]>

  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <%= javascript_include_tag '//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js' %>

<![endif]-->

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

app/views/shared/_header.html.erb
<header>
  <div class="statusbar container full-screen">
    <div class="row">
      <div class="col-sm-12">

        <a href="<%= root_path %>" class="pull-left brand"></a>

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sign-in-navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">Etymology</a>
          </div>
          <% if admin_signed_in? %>
              <div class="pull-right collapse navbar-collapse" id="sign-in-navbar-collapse">
                <% if admin_signed_in? %>
                    <ul class="nav navbar-nav navbar-right">
                      <li>
                        <%= form_tag(destroy_admin_session_path, method: :delete, class: 'navbar-left') do %>
                            <ul class="list-unstyled">
                              <li>
                                <%= current_admin.email %>
                              </li>
                              <li class="sign-in">
                                <button id="logout" type="submit" class="btn-link">
                                  Logout
                                </button>
                              </li>
                            </ul>
                        <% end %>
                      </li>
                    </ul>
                <% else %>
                    <ul class="nav navbar-nav navbar-right">
                      <li class="sign-in">
                        <a id="login" href="<%= new_admin_session_path %>">
                          Sign in / Sign up
                        </a>
                      </li>
                    </ul>
                <% end %>
              </div>
          <% end %>
        </nav>

      </div>
    </div>
  </div>
</header>

app/views/shared/_header_scripts.html.erb
<!--[if lt IE 9]>

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>

<![endif]-->

app/views/shared/_non_rootword_modal.html.erb
<div class="modal fade" id="non-rootword-modal" tabindex="-1" role="dialog" aria-labelledby="NonRootWord" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="NonRootWordLabel">Word</h4>
      </div>
      <div class="modal-body">


        <div class="row ">
          <label class="col-sm-4 col-xs-4 text-right">Word:</label>

          <div class="col-sm-5 col-sm-offset-1">
            <p data-non-rootword="word"></p>
          </div>
        </div>

        <div class="row ">
          <label class="col-sm-4 col-xs-4 text-right">Meaning:</label>

          <div class="col-sm-5 col-sm-offset-1">
            <p data-non-rootword="meaning"></p>
          </div>
        </div>

        <div class="row">
          <label class="col-sm-4 col-xs-4 text-right">Usages:</label>

          <div class="col-sm-5 col-sm-offset-1">
            <ul class="list-unstyled usages-list" data-non-rootword="usages">
            </ul>
          </div>
        </div>

        <div class="row">
          <label class="col-sm-4 col-xs-4 text-right">Root Word:</label>
          <div class="col-sm-5 col-sm-offset-1">
            <button class="btn btn-link btn-lg btn-unstyled" data-target-modal="rootword-modal" data-target='#rootword-modal' data-toggle="modal">
              <div class="hidden rootword-data" data-non-rootword="rootword-data"></div>
              <span data-non-rootword="rootword"></span>
            </button>
          </div>
        </div>



      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_rootword_modal.html.erb
<div class="modal fade" id="rootword-modal" tabindex="-1" role="dialog" aria-labelledby="RootWord" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Root Word</h4>
      </div>
      <div class="modal-body">


        <div class="row ">
          <label class="col-sm-4 col-xs-4 text-right">Word:</label>

          <div class="col-sm-5 col-sm-offset-1">
            <h1 data-rootword="word"></h1>
          </div>
        </div>

        <div class="row ">
          <label class="col-sm-4 col-xs-4 text-right">Meaning:</label>

          <div class="col-sm-5 col-sm-offset-1">
            <h2 data-rootword="meaning"></h2>
          </div>
        </div>

        <div class="row">
          <label class="col-sm-4 col-xs-4 text-right">Usages:</label>

          <div class="col-sm-5 col-sm-offset-1">
            <ul class="list-unstyled usages-list" data-rootword="usages">
            </ul>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_stylesheets.html.erb
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag '//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css' %>